name: A workflow to test group-7-gc application
on: push

jobs:
  IntegrationTests:
    name: Unit and Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run database docker container
        run: |
          docker build -t db ./db
          docker run --name worldDb --hostname db -dp 3306:3306 db
      - name: Unit and integration tests
        run: mvn -Dtest=com.napier.sem.* test
      - name: Stop database docker container
        run: |
          docker stop worldDb
          docker rm worldDb
          docker image rm db
      - name: Update CodeCov reports
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)
          slug: shakad72/group-7-gc

  build:
    name: Execute sample report
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven (skip tests)
        run: mvn package -DskipTests
      - name: Run docker compose
        run:  docker-compose up --abort-on-container-exit